items:
- uid: com.microsoft.azure.management.datalake.analytics.models._inner_error
  id: _inner_error
  parent: com.microsoft.azure.management.datalake.analytics.models
  children:
  - com.microsoft.azure.management.datalake.analytics.models._inner_error_1aa3e4eb1c3c105e098e3aa83b3caff546
  - com.microsoft.azure.management.datalake.analytics.models._inner_error_1a4166ddc55d495ad2d139a9117c79fe7f
  href: com.microsoft.azure.management.datalake.analytics.models._inner_error.yml
  langs:
  - java
  name: InnerError
  fullName: com.microsoft.azure.management.datalake.analytics.models.InnerError
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-datalake-analytics/src/main/java/com/microsoft/azure/management/datalake/analytics/models/InnerError.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-datalake-analytics/src/main/java/com/microsoft/azure/management/datalake/analytics/models/InnerError.java
    startLine: 13
  package: com.microsoft.azure.management.datalake.analytics.models
  summary: <p>Generic resource inner error information. </p>
  syntax:
    content: public class InnerError
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.datalake.analytics.models._inner_error_1aa3e4eb1c3c105e098e3aa83b3caff546
  id: _inner_error_1aa3e4eb1c3c105e098e3aa83b3caff546
  parent: com.microsoft.azure.management.datalake.analytics.models._inner_error
  href: com.microsoft.azure.management.datalake.analytics.models._inner_error.yml
  langs:
  - java
  name: context()
  fullName: String com.microsoft.azure.management.datalake.analytics.models.InnerError.context()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-datalake-analytics/src/main/java/com/microsoft/azure/management/datalake/analytics/models/InnerError.java
    startLine: 40
  package: com.microsoft.azure.management.datalake.analytics.models
  summary: >-
    <p>Get the context value.</p>

    <p></p>
  syntax:
    content: public String context()
    return:
      type: "26831127"
      description: <p>the context value </p>
- uid: com.microsoft.azure.management.datalake.analytics.models._inner_error_1a4166ddc55d495ad2d139a9117c79fe7f
  id: _inner_error_1a4166ddc55d495ad2d139a9117c79fe7f
  parent: com.microsoft.azure.management.datalake.analytics.models._inner_error
  href: com.microsoft.azure.management.datalake.analytics.models._inner_error.yml
  langs:
  - java
  name: trace()
  fullName: String com.microsoft.azure.management.datalake.analytics.models.InnerError.trace()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-datalake-analytics/src/main/java/com/microsoft/azure/management/datalake/analytics/models/InnerError.java
    startLine: 31
  package: com.microsoft.azure.management.datalake.analytics.models
  summary: >-
    <p>Get the trace value.</p>

    <p></p>
  syntax:
    content: public String trace()
    return:
      type: "26831127"
      description: <p>the trace value </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
