items:
- uid: com.microsoft.azure.batch.protocol.models._batch_error_exception
  id: _batch_error_exception
  parent: com.microsoft.azure.batch.protocol.models
  children:
  - com.microsoft.azure.batch.protocol.models._batch_error_exception_1acc84b93b5d29ba9f35b48a5a4cc22edd
  - com.microsoft.azure.batch.protocol.models._batch_error_exception_1a0ae66f2a1eb4847fe778d8ba3783e5ce
  - com.microsoft.azure.batch.protocol.models._batch_error_exception_1a3dad58278576bc16d7eddb693aecde9a
  - com.microsoft.azure.batch.protocol.models._batch_error_exception_1ae009db7c89920903c511e2695fa5a8af
  - com.microsoft.azure.batch.protocol.models._batch_error_exception_1a4eebe94e8b4b2212c0b843575b4116f9
  - com.microsoft.azure.batch.protocol.models._batch_error_exception_1a045358288ecbc85fcfb4e7ef1c5aaf1a
  - com.microsoft.azure.batch.protocol.models._batch_error_exception_1aedda60ce0d2cb4706e68b1e08a42b889
  - com.microsoft.azure.batch.protocol.models._batch_error_exception_1a3460a46512a314b8f27f4406097b6ef3
  href: com.microsoft.azure.batch.protocol.models._batch_error_exception.yml
  langs:
  - java
  name: BatchErrorException
  fullName: com.microsoft.azure.batch.protocol.models.BatchErrorException
  type: Class
  source:
    remote: &o0
      path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/BatchErrorException.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/BatchErrorException.java
    startLine: 14
  package: com.microsoft.azure.batch.protocol.models
  summary: <p>Exception thrown for an invalid response with <xref href="com.microsoft.azure.batch.protocol.models._batch_error" data-throw-if-not-resolved="false"></xref> information. </p>
  syntax: &o1
    content: public class BatchErrorException
  inheritance:
  - Exception
  - com.microsoft.rest._rest_exception
  inheritedMembers:
  - com.microsoft.rest._rest_exception_1a8b86502c682e0b0e47f60b1c33b67b8f
  - com.microsoft.rest._rest_exception_1a8a0b21d2d492219e29a07567ff52b9cf
  - com.microsoft.rest._rest_exception_1ac00611a5b9a02b99e257f2407dc679d5
  - com.microsoft.rest._rest_exception_1ae3378da3ede0800826ccfe5f68532460
- uid: com.microsoft.azure.batch.protocol.models._batch_error_exception_1acc84b93b5d29ba9f35b48a5a4cc22edd
  id: _batch_error_exception_1acc84b93b5d29ba9f35b48a5a4cc22edd
  parent: com.microsoft.azure.batch.protocol.models._batch_error_exception
  href: com.microsoft.azure.batch.protocol.models._batch_error_exception.yml
  langs:
  - java
  name: BatchErrorException()
  fullName: com.microsoft.azure.batch.protocol.models.BatchErrorException.BatchErrorException()
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/BatchErrorException.java
    startLine: 26
  package: com.microsoft.azure.batch.protocol.models
  summary: <p>Initializes a new instance of the <xref href="com.microsoft.azure.batch.protocol.models._batch_error_exception" data-throw-if-not-resolved="false"></xref> class. </p>
  syntax:
    content: public BatchErrorException()
- uid: com.microsoft.azure.batch.protocol.models._batch_error_exception_1a0ae66f2a1eb4847fe778d8ba3783e5ce
  id: _batch_error_exception_1a0ae66f2a1eb4847fe778d8ba3783e5ce
  parent: com.microsoft.azure.batch.protocol.models._batch_error_exception
  href: com.microsoft.azure.batch.protocol.models._batch_error_exception.yml
  langs:
  - java
  name: BatchErrorException(final String message)
  fullName: com.microsoft.azure.batch.protocol.models.BatchErrorException.BatchErrorException(final String message)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/BatchErrorException.java
    startLine: 32
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Initializes a new instance of the <xref href="com.microsoft.azure.batch.protocol.models._batch_error_exception" data-throw-if-not-resolved="false"></xref> class.</p>

    <p></p>
  syntax:
    content: public BatchErrorException(final String message)
    parameters:
    - id: message
      type: 3d93591e
      description: <p>The exception message. </p>
- uid: com.microsoft.azure.batch.protocol.models._batch_error_exception_1a3dad58278576bc16d7eddb693aecde9a
  id: _batch_error_exception_1a3dad58278576bc16d7eddb693aecde9a
  parent: com.microsoft.azure.batch.protocol.models._batch_error_exception
  href: com.microsoft.azure.batch.protocol.models._batch_error_exception.yml
  langs:
  - java
  name: BatchErrorException(final String message, final Throwable cause)
  fullName: com.microsoft.azure.batch.protocol.models.BatchErrorException.BatchErrorException(final String message, final Throwable cause)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/BatchErrorException.java
    startLine: 41
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Initializes a new instance of the <xref href="com.microsoft.azure.batch.protocol.models._batch_error_exception" data-throw-if-not-resolved="false"></xref> class.</p>

    <p></p>
  syntax:
    content: public BatchErrorException(final String message, final Throwable cause)
    parameters:
    - id: message
      type: 3d93591e
      description: <p>the exception message </p>
    - id: cause
      type: fa00b19f
      description: <p>exception that caused this exception to occur </p>
- uid: com.microsoft.azure.batch.protocol.models._batch_error_exception_1ae009db7c89920903c511e2695fa5a8af
  id: _batch_error_exception_1ae009db7c89920903c511e2695fa5a8af
  parent: com.microsoft.azure.batch.protocol.models._batch_error_exception
  href: com.microsoft.azure.batch.protocol.models._batch_error_exception.yml
  langs:
  - java
  name: BatchErrorException(final Throwable cause)
  fullName: com.microsoft.azure.batch.protocol.models.BatchErrorException.BatchErrorException(final Throwable cause)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/BatchErrorException.java
    startLine: 49
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Initializes a new instance of the <xref href="com.microsoft.azure.batch.protocol.models._batch_error_exception" data-throw-if-not-resolved="false"></xref> class.</p>

    <p></p>
  syntax:
    content: public BatchErrorException(final Throwable cause)
    parameters:
    - id: cause
      type: fa00b19f
      description: <p>exception that caused this exception to occur </p>
- uid: com.microsoft.azure.batch.protocol.models._batch_error_exception_1a4eebe94e8b4b2212c0b843575b4116f9
  id: _batch_error_exception_1a4eebe94e8b4b2212c0b843575b4116f9
  parent: com.microsoft.azure.batch.protocol.models._batch_error_exception
  href: com.microsoft.azure.batch.protocol.models._batch_error_exception.yml
  langs:
  - java
  name: getBody()
  fullName: BatchError com.microsoft.azure.batch.protocol.models.BatchErrorException.getBody()
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/BatchErrorException.java
    startLine: 65
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Gets the HTTP response body.</p>

    <p></p>
  syntax:
    content: public BatchError getBody()
    return:
      type: com.microsoft.azure.batch.protocol.models._batch_error
      description: <p>the response body </p>
- uid: com.microsoft.azure.batch.protocol.models._batch_error_exception_1a045358288ecbc85fcfb4e7ef1c5aaf1a
  id: _batch_error_exception_1a045358288ecbc85fcfb4e7ef1c5aaf1a
  parent: com.microsoft.azure.batch.protocol.models._batch_error_exception
  href: com.microsoft.azure.batch.protocol.models._batch_error_exception.yml
  langs:
  - java
  name: getResponse()
  fullName: Response com.microsoft.azure.batch.protocol.models.BatchErrorException.getResponse()
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/BatchErrorException.java
    startLine: 57
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Gets information about the associated HTTP response.</p>

    <p></p>
  syntax:
    content: public Response getResponse()
    return:
      type: e9d34ed6
      description: <p>the HTTP response </p>
- uid: com.microsoft.azure.batch.protocol.models._batch_error_exception_1aedda60ce0d2cb4706e68b1e08a42b889
  id: _batch_error_exception_1aedda60ce0d2cb4706e68b1e08a42b889
  parent: com.microsoft.azure.batch.protocol.models._batch_error_exception
  href: com.microsoft.azure.batch.protocol.models._batch_error_exception.yml
  langs:
  - java
  name: setBody(BatchError body)
  fullName: void com.microsoft.azure.batch.protocol.models.BatchErrorException.setBody(BatchError body)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/BatchErrorException.java
    startLine: 81
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Sets the HTTP response body.</p>

    <p></p>
  syntax:
    content: public void setBody(BatchError body)
    parameters:
    - id: body
      type: com.microsoft.azure.batch.protocol.models._batch_error
      description: <p>the response body </p>
- uid: com.microsoft.azure.batch.protocol.models._batch_error_exception_1a3460a46512a314b8f27f4406097b6ef3
  id: _batch_error_exception_1a3460a46512a314b8f27f4406097b6ef3
  parent: com.microsoft.azure.batch.protocol.models._batch_error_exception
  href: com.microsoft.azure.batch.protocol.models._batch_error_exception.yml
  langs:
  - java
  name: setResponse(Response response)
  fullName: void com.microsoft.azure.batch.protocol.models.BatchErrorException.setResponse(Response response)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/BatchErrorException.java
    startLine: 73
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Sets the HTTP response.</p>

    <p></p>
  syntax:
    content: public void setResponse(Response response)
    parameters:
    - id: response
      type: e9d34ed6
      description: <p>the HTTP response </p>
references:
- uid: 3d93591e
  spec.java:
  - name: final String
    fullName: final String
- uid: fa00b19f
  spec.java:
  - name: final Throwable
    fullName: final Throwable
- uid: e9d34ed6
  spec.java:
  - name: Response
    fullName: Response
- uid: com.microsoft.rest._rest_exception_1a8b86502c682e0b0e47f60b1c33b67b8f
  parent: com.microsoft.rest._rest_exception
  href: com.microsoft.rest._rest_exception.yml
  name: RestException()
  fullName: com.microsoft.rest.RestException.RestException()
  type: Method
  summary: <p>Initializes a new instance of the AutoRestException class. </p>
  syntax:
    content: public RestException()
- uid: com.microsoft.rest._rest_exception_1a8a0b21d2d492219e29a07567ff52b9cf
  parent: com.microsoft.rest._rest_exception
  href: com.microsoft.rest._rest_exception.yml
  name: RestException(String message)
  fullName: com.microsoft.rest.RestException.RestException(String message)
  type: Method
  summary: >-
    <p>Initializes a new instance of the AutoRestException class.</p>

    <p></p>
  syntax:
    content: public RestException(String message)
    parameters:
    - id: message
      type: "26831127"
      description: <p>The exception message. </p>
- uid: com.microsoft.rest._rest_exception_1ac00611a5b9a02b99e257f2407dc679d5
  parent: com.microsoft.rest._rest_exception
  href: com.microsoft.rest._rest_exception.yml
  name: RestException(Throwable cause)
  fullName: com.microsoft.rest.RestException.RestException(Throwable cause)
  type: Method
  summary: >-
    <p>Initializes a new instance of the AutoRestException class.</p>

    <p></p>
  syntax:
    content: public RestException(Throwable cause)
    parameters:
    - id: cause
      type: a04fafd7
      description: <p>exception that caused this exception to occur </p>
- uid: com.microsoft.rest._rest_exception_1ae3378da3ede0800826ccfe5f68532460
  parent: com.microsoft.rest._rest_exception
  href: com.microsoft.rest._rest_exception.yml
  name: RestException(String message, Throwable cause)
  fullName: com.microsoft.rest.RestException.RestException(String message, Throwable cause)
  type: Method
  summary: >-
    <p>Initializes a new instance of the AutoRestException class.</p>

    <p></p>
  syntax:
    content: public RestException(String message, Throwable cause)
    parameters:
    - id: message
      type: "26831127"
      description: <p>the exception message </p>
    - id: cause
      type: a04fafd7
      description: <p>exception that caused this exception to occur </p>
- uid: com.microsoft.rest._rest_exception
  parent: com.microsoft.rest
  href: com.microsoft.rest._rest_exception.yml
  name: RestException
  fullName: com.microsoft.rest.RestException
  type: Class
  summary: <p>Exception thrown for an invalid response with custom error information. </p>
  syntax:
    content: public class RestException
- uid: com.microsoft.azure.batch._create_tasks_terminated_exception
  parent: com.microsoft.azure.batch
  href: com.microsoft.azure.batch._create_tasks_terminated_exception.yml
  name: CreateTasksTerminatedException
  fullName: com.microsoft.azure.batch.CreateTasksTerminatedException
  type: Class
  syntax:
    content: public class CreateTasksTerminatedException
- uid: com.microsoft.azure.batch.protocol.models._batch_error
  parent: com.microsoft.azure.batch.protocol.models
  href: com.microsoft.azure.batch.protocol.models._batch_error.yml
  name: BatchError
  fullName: com.microsoft.azure.batch.protocol.models.BatchError
  type: Class
  summary: <p>An error response received from the <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref> Batch service. </p>
  syntax:
    content: public class BatchError
- uid: com.microsoft.azure.batch.protocol.models._batch_error_exception
  parent: com.microsoft.azure.batch.protocol.models
  href: com.microsoft.azure.batch.protocol.models._batch_error_exception.yml
  name: BatchErrorException
  fullName: com.microsoft.azure.batch.protocol.models.BatchErrorException
  type: Class
  summary: <p>Exception thrown for an invalid response with <xref href="com.microsoft.azure.batch.protocol.models._batch_error" data-throw-if-not-resolved="false"></xref> information. </p>
  syntax: *o1
